// sync-catalog.mjs — reshape the catalog into the JSON the site reads.
//
// Single source: ../images/catalog.lock.yaml (generated by images/scripts/
// gen-catalog.py). The lock already carries everything per app — editorial
// (category/summary/upstream/cleanAlternative), license/tier/status, arches,
// and every published version with size/digest/date. This script just converts
// that into src/data/{images,charts}.json. Charts also read the
// chart dirs under ../charts/quench for chart-version/port facts.
//
// Run: `node scripts/sync-catalog.mjs` (wired into predev/prebuild).

import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse as parseYaml } from 'yaml';

const here = dirname(fileURLToPath(import.meta.url));
const websiteRoot = resolve(here, '..');
const repoRoot = resolve(websiteRoot, '..'); // __QuenchWorks__
const catalogLock = resolve(repoRoot, 'images', 'catalog.lock.yaml');
const chartsDir = resolve(repoRoot, 'charts', 'quench');
const outDir = resolve(websiteRoot, 'src', 'data');
const ghcr = 'ghcr.io/quenchworks';

// quench-common is a Helm library chart, not an image; never in either index.
const EXCLUDE = new Set(['quench-common']);
// status -> published? built/done/pilot all mean "an image exists".
const PUBLISHED = new Set(['built', 'done', 'pilot']);

// ──────────────────────────────────────────────────────────────────────────
// helpers
// ──────────────────────────────────────────────────────────────────────────
function readYamlSafe(path) {
  try {
    if (!existsSync(path)) return null;
    return parseYaml(readFileSync(path, 'utf8'));
  } catch (err) {
    console.warn(`! could not parse ${path}: ${err.message}`);
    return null;
  }
}

// Normalize SPDX-ish license strings (catalog uses `-only`/`-or-later` suffixes).
function normalizeLicense(raw) {
  if (!raw) return 'Unknown';
  return String(raw).replace(/-only$/, '').replace(/-or-later$/, '+').trim();
}

// clean | agpl | caution
function deriveLicenseClean(license) {
  const l = (license || '').toUpperCase();
  if (l.includes('BSL') || l.includes('BUSL') || l.includes('SSPL')) return 'caution';
  if (l.includes('AGPL') || l.startsWith('GPL-3')) return 'agpl';
  return 'clean'; // Apache/BSD/MIT/PostgreSQL/MPL/GPL-2.0 etc.
}

function servicePort(values) {
  const svc = values?.service;
  if (svc && (typeof svc.port === 'number' || typeof svc.port === 'string')) return svc.port;
  return undefined;
}

// Pretty-print app names (catalog slugs are lowercase).
const NAME = {
  postgresql: 'PostgreSQL', 'postgresql-15': 'PostgreSQL 15', 'postgres-documentdb': 'PostgreSQL + DocumentDB',
  mariadb: 'MariaDB', mysql: 'MySQL', cockroachdb: 'CockroachDB', couchdb: 'CouchDB',
  documentdb: 'DocumentDB', ferretdb: 'FerretDB', mongodb: 'MongoDB', scylladb: 'ScyllaDB',
  clickhouse: 'ClickHouse', opensearch: 'OpenSearch', elasticsearch: 'Elasticsearch',
  influxdb: 'InfluxDB', victoriametrics: 'VictoriaMetrics', neo4j: 'Neo4j', rabbitmq: 'RabbitMQ',
  nats: 'NATS', zookeeper: 'ZooKeeper', etcd: 'etcd', valkey: 'Valkey', redis: 'Redis',
  dragonfly: 'Dragonfly', memcached: 'Memcached', kafka: 'Kafka', pulsar: 'Pulsar',
  cassandra: 'Cassandra', solr: 'Solr', nginx: 'nginx', haproxy: 'HAProxy', caddy: 'Caddy',
  traefik: 'Traefik', keycloak: 'Keycloak', openbao: 'OpenBao', qdrant: 'Qdrant',
  meilisearch: 'Meilisearch', seaweedfs: 'SeaweedFS', garage: 'Garage', rustfs: 'RustFS',
  prometheus: 'Prometheus', grafana: 'Grafana', loki: 'Loki', tempo: 'Tempo', vector: 'Vector',
  'otel-collector': 'OpenTelemetry Collector', 'fluent-bit': 'Fluent Bit', alertmanager: 'Alertmanager',
  temporal: 'Temporal', 'temporal-cli': 'Temporal CLI', atlantis: 'Atlantis', gitea: 'Gitea',
  'coolify-app': 'Coolify', 'coolify-helper': 'Coolify Helper', 'coolify-realtime': 'Coolify Realtime',
  busybox: 'BusyBox',
};
function prettyName(slug) {
  if (NAME[slug]) return NAME[slug];
  if (slug.startsWith('harbor-')) return 'Harbor ' + slug.slice(7);
  return slug;
}

// ──────────────────────────────────────────────────────────────────────────
// read the lock
// ──────────────────────────────────────────────────────────────────────────
const lockDoc = readYamlSafe(catalogLock);
const lockApps = lockDoc && typeof lockDoc.apps === 'object' && lockDoc.apps ? lockDoc.apps : {};

// CI/website-only build: the sibling images repo isn't checked out, so the lock
// is absent. The committed src/data/*.json IS the build input — keep it.
if (!Object.keys(lockApps).length) {
  if (existsSync(resolve(outDir, 'images.json')) && existsSync(resolve(outDir, 'charts.json'))) {
    console.warn(`! ${catalogLock} not found — keeping committed src/data/*.json (expected in a website-only/CI build).`);
    process.exit(0);
  }
  console.error(`✗ ${catalogLock} not found and no committed src/data/*.json. Generate it: (cd ../images && uv run scripts/gen-catalog.py --meta)`);
  process.exit(1);
}

// ──────────────────────────────────────────────────────────────────────────
// 1) images.json — straight reshape of the lock
// ──────────────────────────────────────────────────────────────────────────
const images = [];
for (const [slug, a] of Object.entries(lockApps)) {
  if (EXCLUDE.has(slug)) continue;
  const license = normalizeLicense(a.license);
  const licenseClean = deriveLicenseClean(license);
  const versions = (Array.isArray(a.versions) ? a.versions : []).map((v) => ({
    version: String(v.version),
    size: v.size ?? undefined,
    published: v.published ?? undefined,
    digest: v.digest ?? undefined,
  }));

  const entry = {
    slug,
    name: prettyName(slug),
    category: a.category || 'Datastore',
    summary: a.summary || `Hardened ${slug} image, built from source on Wolfi.`,
    tier: String(a.tier || 'standard'),
    status: PUBLISHED.has(String(a.status)) ? 'available' : 'planned',
    license,
    licenseClean,
    version: versions.length ? versions.map((v) => v.version).join(', ') : undefined,
    versions: versions.length ? versions : undefined,
    arches: Array.isArray(a.arches) ? a.arches : undefined,
    upstream: a.upstream || a.source || '',
    source: a.source || '',
    image: a.image || `${ghcr}/images/${slug}`,
  };
  if (licenseClean === 'caution') {
    entry.caution = true;
    if (a.cleanAlternative) entry.cleanAlternative = a.cleanAlternative;
  }
  images.push(entry);
}

// ──────────────────────────────────────────────────────────────────────────
// 2) charts.json — chart dirs + per-app editorial/license from the lock
// ──────────────────────────────────────────────────────────────────────────
const charts = [];
let chartDirs = [];
try {
  chartDirs = readdirSync(chartsDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .filter((n) => !EXCLUDE.has(n));
} catch (err) {
  console.warn(`! could not read charts dir ${chartsDir}: ${err.message}`);
}

for (const slug of chartDirs.sort()) {
  const dir = resolve(chartsDir, slug);
  const chartYaml = readYamlSafe(resolve(dir, 'Chart.yaml'));
  const valuesYaml = readYamlSafe(resolve(dir, 'values.yaml'));
  const ahRepo = readYamlSafe(resolve(dir, 'artifacthub-repo.yml'));
  const a = lockApps[slug] || {};
  const license = a.license ? normalizeLicense(a.license) : 'Unknown';
  const licenseClean = deriveLicenseClean(license);
  const img = valuesYaml?.image || {};
  const newestVer = a.versions?.[0]?.version;
  const desc = chartYaml?.description ? String(chartYaml.description) : undefined;

  // A "stack" is an umbrella chart over several component charts — it has no
  // single backing image, so it must NOT get an imageRepository/digest/port or
  // the generic "hardened image" summary. Detected by the `-stack` naming
  // convention. Its components are listed from the chart's OCI dependencies.
  const isStack = slug.endsWith('-stack');
  const components = isStack
    ? (Array.isArray(chartYaml?.dependencies) ? chartYaml.dependencies : [])
        .map((d) => d?.name)
        .filter((n) => n && n !== 'quench-common')
    : undefined;

  // Every image the chart deploys, from the artifacthub.io/images annotation
  // (a YAML string). Stacks bundle many; single-app charts list their 1-2.
  let chartImages;
  try {
    const raw = chartYaml?.annotations?.['artifacthub.io/images'];
    const parsed = raw ? parseYaml(String(raw)) : null;
    if (Array.isArray(parsed)) {
      chartImages = parsed
        .map((i) => ({ name: String(i?.name || ''), image: String(i?.image || '') }))
        .filter((i) => i.image);
    }
  } catch (err) {
    console.warn(`! ${slug}: could not parse artifacthub.io/images: ${err.message}`);
  }

  // Stacks have no single upstream — list the bundled components' upstream
  // projects from Chart.yaml sources (drop the quenchworks self-refs).
  const upstreams = isStack && Array.isArray(chartYaml?.sources)
    ? chartYaml.sources.map(String).filter((s) => !/github\.com\/quenchworks/i.test(s))
    : undefined;

  const entry = {
    slug,
    name: prettyName(chartYaml?.name || slug),
    category: isStack ? 'Stacks' : (a.category || 'Datastore'),
    summary:
      a.summary ||
      (isStack && desc ? desc.split('. ')[0].replace(/\.$/, '') + '.' : `Hardened ${slug} image, built from source on Wolfi.`),
    tier: String(a.tier || 'standard'),
    license,
    licenseClean,
    chartVersion: chartYaml?.version != null ? String(chartYaml.version) : undefined,
    appVersion: chartYaml?.appVersion != null ? String(chartYaml.appVersion) : (newestVer ?? undefined),
    description: desc,
    // image facts only for single-app charts; stacks are chart-only umbrellas.
    imageRepository: isStack ? undefined : img.repository ? String(img.repository) : `${ghcr}/images/${slug}`,
    imageDigest: isStack ? undefined : img.digest ? String(img.digest) : undefined,
    repositoryID: ahRepo?.repositoryID ? String(ahRepo.repositoryID) : undefined,
    port: isStack ? undefined : servicePort(valuesYaml),
    upstream: a.upstream || a.source || (chartYaml?.home ? String(chartYaml.home) : '') || '',
    chartRef: `oci://${ghcr}/charts/${slug}`,
    stack: isStack || undefined,
    components: components && components.length ? components : undefined,
    images: chartImages && chartImages.length ? chartImages : undefined,
    upstreams: upstreams && upstreams.length ? upstreams : undefined,
  };
  if (licenseClean === 'caution') {
    entry.caution = true;
    if (a.cleanAlternative) entry.cleanAlternative = a.cleanAlternative;
  }
  charts.push(entry);
}

// ──────────────────────────────────────────────────────────────────────────
// 3) write outputs (images: available first then alpha; charts alpha). Per-
//    version size/date/digest live in images.json versions[]; there is no
//    separate image-meta.json anymore.
// ──────────────────────────────────────────────────────────────────────────
images.sort((a, b) => {
  const sa = a.status === 'available' ? 0 : 1;
  const sb = b.status === 'available' ? 0 : 1;
  return sa !== sb ? sa - sb : a.name.localeCompare(b.name);
});
charts.sort((a, b) => a.name.localeCompare(b.name));

writeFileSync(resolve(outDir, 'images.json'), JSON.stringify(images, null, 2) + '\n');
writeFileSync(resolve(outDir, 'charts.json'), JSON.stringify(charts, null, 2) + '\n');

const avail = images.filter((i) => i.status === 'available').length;
const cautionCount = images.filter((i) => i.caution).length;
console.log(
  `sync-catalog: ${images.length} images (${avail} available), ${charts.length} charts, ${cautionCount} caution.`,
);
